proyecto_2021/app_bases/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views

from app_bases.views import Home

app_name = 'app_bases'
urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name="logout"),
]

proyecto_2021/app_inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
                   SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel

app_name = "app_inv"
urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),
    
    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategoria/new', SubCategoriaNew.as_view(), name="subcategoria_new"),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),
]

proyecto_2021/proyecto_2021/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_bases.urls', namespace="bases")),
    path('inv/', include('app_inv.urls', namespace="inv")),
]

proyecto_2021/app_bases/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class ClaseModelo(models.Model):

    estado = models.BooleanField(default=True)

    fc = models.DateTimeField(auto_now_add=True)

    fm = models.DateTimeField(auto_now=True)

    uc = models.ForeignKey(User, on_delete=models.CASCADE)

    um = models.IntegerField(blank=True, null=True)

    # No a producción

    class Meta:
        abstract = True

proyecto_2021/app_inv/models.py
from django.db import models

from app_bases.models import ClaseModelo

# Create your models here.

class Categoria(ClaseModelo):

    descripcion = models.CharField(
        
        max_length=100,

        help_text = 'Descripción del maiki',

        unique = True

    )

    def __str__(self):
        return f'{self.descripcion}'

    # Cuando hacen referencia a la categoria va mostrar la descripcion de la categoria

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = 'Categorias'

class SubCategoria(ClaseModelo):

    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)

    descripcion = models.CharField(
        
        max_length=100,

        help_text = 'Descripción de la Categoría'

    )

    def __str__(self):

        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)
        #cuando hacen referencia a subcategoria va mostrar la descripcion de la categoria y la descripcion de la subcategoria
        #   pantalones:pantalones para niños

    def save(self):
        self.descripcion = self.descripcion.upper()

        super(SubCategoria, self).save()

    class Meta:

        verbose_name_plural = "Sub Categorías"

        unique_together = ('categoria', 'descripcion')

proyecto_2021/app_inv/forms.py
from django import forms

from .models import Categoria, SubCategoria

class CategoriaForm(forms.ModelForm):

    class Meta:
        model = Categoria

        fields = [
            'descripcion', 'estado'
        ]

        labels = {
            "descripcion": "Descripción de la Categoría",
            "estado": "Estado"
        }

        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class SubCategoriaForm(forms.ModelForm):
    #para que no muestre los que tienen estado false
    categoria = forms.ModelChoiceField(
        queryset = Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )

    class Meta:

        model = SubCategoria

        fields = [
            'categoria', 'descripcion', 'estado'
        ]

        labels = {
            "descripcion": "Sub Categoría",
            "estado": "Estado"
        }

        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)

        for field in iter(self.fields):

            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': 'Descripción de la SubCategoría'
            })
        
        self.fields['categoria'].empty_label = "Seleccione la Categoría"

proyecto_2021/app_bases/views.py
from django.shortcuts import render, redirect

from django.views import generic

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class Home(LoginRequiredMixin, generic.TemplateView):
    template_name = 'bases/home.html'

    login_url = '/login/'

proyecto_2021/app_inv/views.py
from django.shortcuts import render

from  django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic

from .models import Categoria, SubCategoria

from .forms import CategoriaForm, SubCategoriaForm

from django.urls import reverse_lazy

# Create your views here.

class CategoriaView(LoginRequiredMixin, generic.ListView):

    model = Categoria

    template_name = "inv/categorias_list.html"

    context_object_name = "obj"

    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):

    model = Categoria

    template_name = 'inv/categorias_form.html'

    context_object_name = "obj"

    form_class = CategoriaForm

    success_url = reverse_lazy("inv:categoria_list")

    login_url = 'bases:login'

    def form_valid(self, form):

        form.instance.uc = self.request.user

        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):

    model = Categoria

    template_name = 'inv/categorias_form.html'

    context_object_name = "obj"

    form_class = CategoriaForm

    success_url = reverse_lazy("inv:categoria_list")

    login_url = 'bases:login'

    def form_valid(self, form):

        form.instance.um = self.request.user.id

        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):

    model = Categoria

    template_name = 'inv/catalogos_del.html'

    context_object_name = 'obj'

    success_url = reverse_lazy("inv:categoria_list")

class SubCategoriaView(LoginRequiredMixin, generic.ListView):

    model = SubCategoria

    template_name = "inv/subcategorias_list.html"

    context_object_name = "obj"

    login_url = 'bases:login'

class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):

    model = SubCategoria

    template_name = "inv/subcategorias_form.html"

    context_object_name = "obj"

    form_class = SubCategoriaForm

    success_url = reverse_lazy("inv:subcategoria_list")

    login_url = 'bases:login'

    def form_valid(self, form):

        form.instance.uc = self.request.user

        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):

    model = SubCategoria

    template_name = 'inv/subcategorias_form.html'

    context_object_name = "obj"

    form_class = SubCategoriaForm

    success_url = reverse_lazy("inv:subcategoria_list")

    login_url = 'bases:login'

    def form_valid(self, form):

        form.instance.um = self.request.user.id

        return super().form_valid(form)

class SubCategoriaDel(LoginRequiredMixin, generic.DeleteView):

    model = SubCategoria

    template_name = 'inv/catalogos_del.html'

    context_object_name = "obj"

    success_url = reverse_lazy("inv:subcategoria_list")

proyecto_2021/app_bases/templates/bases/home.html
{% extends 'bases/bases.html' %}

proyecto_2021/app_bases/templates/bases/login.html
{% extends 'bases/bases.html' %}

{% block side_bar %} {% endblock %}
{% block top_bar %} {% endblock %}
{% block page_content %} {% endblock %}
{% block footer %} {% endblock %}

{% block login %}

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>

                                        <small class="text-danger">

                                            {% if form.errors %}
                                                {% for field in form %}
                                                    {% if field.errors %}
                                                        {% for error in field.errors %}
                                                            {{ error|escape }}
                                                        {% endfor %}
                                                    {% endif %}
                                                {% endfor %}

                                                {% if form.non_field_errors %}
                                                    {% for error in form.non_field_errors %}
                                                        {{ error|escape }}
                                                    {% endfor %}
                                                {% endif %}

                                            {% endif %}

                                            <br><br>

                                        </small>
                                    </div>
                                    <form class="user" method="POST">
                                        {% csrf_token %}

                                        <div class="form-group">
                                            <input type="text" name="username" class="form-control form-control-user"
                                                id="id_username" autofocus required placeholder="Ingresa el usuario">
                                        </div>

                                        <div class="form-group">
                                            <input type="password" name = "password" class="form-control form-control-user"
                                                id="ids_password" placeholder="Password" required>
                                        </div>

                                        {#{ form.as_p  }#}

                                        <button type="submit" class="btn btn-primary btn-user btn-block">
                                            Acceder al sistema
                                        </button>
                                        <hr>

                                        <!-- {{ form.as_p }} -->

                                    </form>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

</body>

</html>

{% endblock %}

proyecto_2021/app_inv/templates/inv/catalogos_del.html
{% extends 'bases/bases.html' %}

{% block page_content %}
    <form method="POST" class="form-inline">

        {% csrf_token %}

        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-danger shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                ¿Eliminar {{ obj.descripcion }}?
                            </div>
                            <button type="submit" class="btn btn-danger">
                                <i class="far fa-question-circle"></i>
                                Sí, eliminar
                            </button>

                            <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success">
                                <span class="fa fa-undo"></span>
                                Cancelar
                            </a>
                        </div>
                        <div class="col-auto">
                            <i class="far fa-question-circle fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

proyecto_2021/app_inv/templates/inv/categorias_form.html
{% extends 'bases/bases.html' %}

{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">

        {% if obj %}
        
            <div class="card border-left-warning shadow h-100 py-2">
        
        {% else %}

            <div class="card border-left-success shadow h-100 py-2">
        
        {% endif %}

            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Categoría
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">

                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="descripcion" maxlength="100" class="form-control" id = "id_descripcion" required
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                            </div>
                        </div>

                        <div class="col-2">
                            <div class="input-group">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id = "id_estado"
                                {% if obj %}
                                    {% if obj.estado %} checked {% endif %}
                                {% else %}
                                    checked
                                {% endif %}
                                >
                            </div>
                        </div>

                        <!--{{ form.as_p }}-->
                    
                    </div>

                        <div class="dropdown-divider"></div>

                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger">
                                    <span class="fa fa-save"></span>
                                    Guardar
                                </button>

                                <a href="{% url 'inv:categoria_list' %}" class="btn btn-success">
                                    <span class="fa fa-undo"></span>
                                    Cancelar
                                </a>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block js_page %}



{% endblock %}

proyecto_2021/app_inv/templates/inv/categorias_list.html
{% extends 'bases/bases.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Categorías</h6>
        <!--<a class="btn btn-success derecha" href="{% url 'inv:categoria_new' %}">Nueva</a>-->
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:categoria_new' %}">Nueva categoría</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Salir</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">

        {% if not obj %}

            No hay Categorías

        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif</th>
                <th class="all">Acciones</th>
            </thead>
       
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{% if item.estado %} Activado {% else %} Desactivado {% endif %}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:categoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button">
                                <i class="far fa-edit"></i>
                            </a>

                            <a href="{% url 'inv:categoria_del' item.id %}" class="btn btn-danger btn-circle" role="button">
                                <i class="far fa-trash-alt"></i>
                            </a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}

    </div>
</div>

{% endblock %}

{% block js_page %}

<script>

$(document).ready( function () {
    $('.table').DataTable();
} );

</script>

{% endblock %}

proyecto_2021/app_inv/templates/inv/subcategorias_form.html
{% extends 'bases/bases.html' %}

{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">

        {% if obj %}
        
            <div class="card border-left-warning shadow h-100 py-2">
        
        {% else %}

            <div class="card border-left-success shadow h-100 py-2">
        
        {% endif %}

            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} SubCategoría
                        </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">

                        <div class="col-5">

                            <div class="input-group">

                                {{ form.categoria }}

                            </div>

                        </div>

                        <div class="col-5">

                            <div class="input-group">
                                <!--
                                
                                <div class="col-5">
                                    <div class="input-group">
                                        <input type="text" name="descripcion" maxlength="100" class="form-control" id = "id_descripcion" required
                                        value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                                    </div>
                                </div>
                                
                                -->

                                {{ form.descripcion }}

                            </div>

                        </div>

                        <div class="col-2">
                            <div class="input-group">
                                <!--
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id = "id_estado"
                                {% if obj %}
                                    {% if obj.estado %} checked {% endif %}
                                {% else %}
                                    checked
                                {% endif %}
                                >
                                -->

                                {{ form.estado }}

                            </div>
                        </div>

                        {#{ form.as_p }#}

                    </div>

                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger">
                                <span class="fa fa-save"></span>
                                Guardar
                            </button>
                            <a href="{% url 'inv:subcategoria_list' %}" class="btn btn-success">
                                <span class="fa fa-undo"></span>
                                Cancelar
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

{% block js_page %}



{% endblock %}

proyecto_2021/app_inv/templates/inv/subcategorias_list.html
{% extends 'bases/bases.html' %}

{% block page_content %}

<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div
        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Listado de Sub Categorías</h6>
        <!--<a class="btn btn-success derecha" href="{% url 'inv:categoria_new' %}">Nueva</a>-->
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in"
                aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:subcategoria_new' %}">Nueva sub categoría</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Salir</a>
            </div>
        </div>
    </div>
    <!-- Card Body -->
    <div class="card-body">

        {% if not obj %}

            No hay Sub Categorías

        {% else %}

        <table class="table table-striped table-hover">
            <thead>
                <th>Categoría</th>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>F. Creado</th>
                <th>F. Modif</th>
                <th class="all">Acciones</th>
            </thead>
       
            <tbody>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.categoria }}</td>
                        <td>{{ item.id }}</td>
                        <td>{{ item.descripcion }}</td>
                        <td>{% if item.estado %} Activado {% else %} Desactivado {% endif %}</td>
                        <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                        <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                        <td>
                            <a href="{% url 'inv:subcategoria_edit' item.id %}" class="btn btn-warning btn-circle" role="button">
                                <i class="far fa-edit"></i>
                            </a>

                            <a href="{% url 'inv:subcategoria_del' item.id %}" class="btn btn-danger btn-circle" role="button">
                                <i class="far fa-trash-alt"></i>
                            </a>

                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% endif %}

    </div>
</div>

{% endblock %}

{% block js_page %}

    <script>

        $(document).ready( function () {
            $('.table').DataTable();
        } );

    </script>

{% endblock %}